on: push
name:  Deploy website on push
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name:  Get latest code
      uses: actions/checkout@v2.3.2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2

    - name:  Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.syedhussnainshah.tech
        username: syedhussnainshah.tech
        password: toptrendingsite@sf
        server-dir: public_html/deploy/shayansolutions/
